version: '3.9'

services:

  postgres:
    image: postgres:17
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    container_name: postgres
    user: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 10s
      retries: 5
    secrets:
      - db_password
    ports:
      - 5432:5432

  pgadmin4:
    image: elestio/pgadmin
    restart: always
    container_name: pgAdmin
    environment:
      PGADMIN_DEFAULT_EMAIL: adityadash300@gmail.com
      PGADMIN_DEFAULT_PASSWORD: pgAdminPass
      PGADMIN_LISTEN_PORT: 8080
    ports:
    - 8080:8080
    volumes:
    - pg_admin_data:/pgadmin4/


# Create a file named db_password relative to docker compose file to run the image
secrets:
  db_password:
    file: db_password

volumes:
  postgres_data:
  pg_admin_data: